FROM kalilinux/kali-rolling

# Installer les outils requis
RUN apt-get update && apt-get install -y \
    nmap hydra openssh-server && \
    apt-get clean

# Configurer SSH
RUN echo "root:root" | chpasswd
RUN mkdir -p /var/run/sshd

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
