version: "3.8"
services:
  kali:
    build: ./kali
    networks:
      - cybernet
    tty: true
    stdin_open: true
  target:
    build: ./target
    networks:
      - cybernet
  logs:
    build: ./logs
    networks:
      - cybernet
    ports:
      - "5000:5000" # Expose le tableau de bord sur localhost:5000
networks:
  cybernet:
    driver: bridge
