version: '3.8'

services:
  attaque:
    build:
      context: .
      dockerfile: Dockerfile_attaque
    networks:
      - cyber-network
    ports:
      - "2222:22"

  logs:
    build:
      context: .
      dockerfile: Dockerfile_logs
    networks:
      - cyber-network
    ports:
      - "8080:80"
      - "2223:22"

  victime:
    build:
      context: .
      dockerfile: Dockerfile_victime
    networks:
      - cyber-network
    ports:
      - "2224:22"

networks:
  cyber-network:
    driver: bridge
