- name: Deploy machine attaque
  hosts: attaque
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nmap
          - hydra
          - openssh-server
        state: present
        update_cache: yes

    - name: Ensure SSH is running
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true

- name: Deploy machine logs
  hosts: logs
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - iputils-ping
          - iproute2
          - apache2
        state: present
        update_cache: yes

    - name: Ensure SSH is running
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true

- name: Deploy machine victime
  hosts: victime
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - iputils-ping
          - iproute2
          - apache2
        state: present
        update_cache: yes

    - name: Ensure SSH is running
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true

